name: Upload Python Package

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        target-version: [py38, py39, py310, py311, py312]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: "3.12"
    - name: Build package 👷‍♂️
      run: |
        pdm install
        PDM_BUILD_SCM_VERSION=${{ github.ref_name }} PYFUTURE_TARGET=${{ matrix.target-version }} pdm build --no-isolation
    - name: Upload wheels 👷‍♂️
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Download wheels 👷‍♂️
      uses: actions/download-artifact@v3
      with:
        name: wheels
        path: dist
    - name: Publish to PyPi 🚀
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        packages-dir: dist
        verbose: true
    - name: Publish GitHub Release 📝
      uses: softprops/action-gh-release@v1
      with:
        name: "PyFuture Release ${{ github.ref }}"
        files: |
          dist/*
